//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyFrish_Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Alapadatok {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alapadatok() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilyFrish_Demo.Resources.Alapadatok", typeof(Alapadatok).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs jogosultsága a leltárlekéréshez!.
        /// </summary>
        public static string ErrorInvalidInventoryPermission {
            get {
                return ResourceManager.GetString("ErrorInvalidInventoryPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs jogosultsága belépni a rendszerbe!.
        /// </summary>
        public static string ErrorInvalidPremission {
            get {
                return ResourceManager.GetString("ErrorInvalidPremission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen felhasználó vagy jelszó!.
        /// </summary>
        public static string ErrorInvalUduser {
            get {
                return ResourceManager.GetString("ErrorInvalUduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megadása kötelező!.
        /// </summary>
        public static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév megadása kötelező!.
        /// </summary>
        public static string ErrorUserName {
            get {
                return ResourceManager.GetString("ErrorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzés:.
        /// </summary>
        public static string InventoryComment {
            get {
                return ResourceManager.GetString("InventoryComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leltár azonosító:.
        /// </summary>
        public static string InventoryId {
            get {
                return ResourceManager.GetString("InventoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leltár kezdete:.
        /// </summary>
        public static string InventoryRecordBegin {
            get {
                return ResourceManager.GetString("InventoryRecordBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítés bezárása.
        /// </summary>
        public static string InventoryRecordClose {
            get {
                return ResourceManager.GetString("InventoryRecordClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leltár tervezett vége:.
        /// </summary>
        public static string InventoryRecordEnd {
            get {
                return ResourceManager.GetString("InventoryRecordEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzízés megnyitása.
        /// </summary>
        public static string InventoryRecordOpen {
            get {
                return ResourceManager.GetString("InventoryRecordOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz:.
        /// </summary>
        public static string InventoryState {
            get {
                return ResourceManager.GetString("InventoryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belépés.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string LoginHeaderMessage {
            get {
                return ResourceManager.GetString("LoginHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzített tételek száma:.
        /// </summary>
        public static string NumberOfFixeditems {
            get {
                return ResourceManager.GetString("NumberOfFixeditems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vonalkód.
        /// </summary>
        public static string SearchItemModalBarCode {
            get {
                return ResourceManager.GetString("SearchItemModalBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégsem.
        /// </summary>
        public static string SearchItemModalCancel {
            get {
                return ResourceManager.GetString("SearchItemModalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzés.
        /// </summary>
        public static string SearchItemModalComment {
            get {
                return ResourceManager.GetString("SearchItemModalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        public static string SearchItemModalDelete {
            get {
                return ResourceManager.GetString("SearchItemModalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzít.
        /// </summary>
        public static string SearchItemModalDone {
            get {
                return ResourceManager.GetString("SearchItemModalDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talált mennyiség.
        /// </summary>
        public static string SearchItemModalFindCount {
            get {
                return ResourceManager.GetString("SearchItemModalFindCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítés dátuma.
        /// </summary>
        public static string SearchItemModalItemCommitDate {
            get {
                return ResourceManager.GetString("SearchItemModalItemCommitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utolsó módosítás dátuma.
        /// </summary>
        public static string SearchItemModalItemLastModifiedDate {
            get {
                return ResourceManager.GetString("SearchItemModalItemLastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utolsó módosító felhasználó.
        /// </summary>
        public static string SearchItemModalItemLastModifiedUsername {
            get {
                return ResourceManager.GetString("SearchItemModalItemLastModifiedUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikknév.
        /// </summary>
        public static string SearchItemModalItemName {
            get {
                return ResourceManager.GetString("SearchItemModalItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikkszám.
        /// </summary>
        public static string SearchItemModalItemNumber {
            get {
                return ResourceManager.GetString("SearchItemModalItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítő felhasználó.
        /// </summary>
        public static string SearchItemModalItemUserame {
            get {
                return ResourceManager.GetString("SearchItemModalItemUserame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkciók.
        /// </summary>
        public static string StartNavigationValue {
            get {
                return ResourceManager.GetString("StartNavigationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres bejelentkezés!.
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vonalkód.
        /// </summary>
        public static string TableHeaderBarCode {
            get {
                return ResourceManager.GetString("TableHeaderBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mennyiség.
        /// </summary>
        public static string TableHeaderItemCount {
            get {
                return ResourceManager.GetString("TableHeaderItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikk.
        /// </summary>
        public static string TableHeaderItemName {
            get {
                return ResourceManager.GetString("TableHeaderItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikkszám.
        /// </summary>
        public static string TableHeaderItemNumber {
            get {
                return ResourceManager.GetString("TableHeaderItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vonalkód.
        /// </summary>
        public static string UpdateInventoryBarCode {
            get {
                return ResourceManager.GetString("UpdateInventoryBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikknév.
        /// </summary>
        public static string UpdateInventoryItemName {
            get {
                return ResourceManager.GetString("UpdateInventoryItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikkszám.
        /// </summary>
        public static string UpdateInventoryItemNumber {
            get {
                return ResourceManager.GetString("UpdateInventoryItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        public static string UpdateInventorySearch {
            get {
                return ResourceManager.GetString("UpdateInventorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felvitel.
        /// </summary>
        public static string UpdateInventoryUpload {
            get {
                return ResourceManager.GetString("UpdateInventoryUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vonalkód.
        /// </summary>
        public static string UpdateItemModalBarCode {
            get {
                return ResourceManager.GetString("UpdateItemModalBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégsem.
        /// </summary>
        public static string UpdateItemModalCancel {
            get {
                return ResourceManager.GetString("UpdateItemModalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzés.
        /// </summary>
        public static string UpdateItemModalComment {
            get {
                return ResourceManager.GetString("UpdateItemModalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzít.
        /// </summary>
        public static string UpdateItemModalDone {
            get {
                return ResourceManager.GetString("UpdateItemModalDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talált mennyiség.
        /// </summary>
        public static string UpdateItemModalFindCount {
            get {
                return ResourceManager.GetString("UpdateItemModalFindCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikknév.
        /// </summary>
        public static string UpdateItemModalItemName {
            get {
                return ResourceManager.GetString("UpdateItemModalItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cikkszám.
        /// </summary>
        public static string UpdateItemModalItemNumber {
            get {
                return ResourceManager.GetString("UpdateItemModalItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár:.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs nyitott leltár!.
        /// </summary>
        public static string WarnNoOpenInventory {
            get {
                return ResourceManager.GetString("WarnNoOpenInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem.
        /// </summary>
        public static string YesNoModalNo {
            get {
                return ResourceManager.GetString("YesNoModalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igen.
        /// </summary>
        public static string YesNoModalYes {
            get {
                return ResourceManager.GetString("YesNoModalYes", resourceCulture);
            }
        }
    }
}
