//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyFrish_Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Alapadatok {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alapadatok() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilyFrish_Demo.Resources.Alapadatok", typeof(Alapadatok).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzés:.
        /// </summary>
        public static string InventoryComment {
            get {
                return ResourceManager.GetString("InventoryComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leltár azonosító:.
        /// </summary>
        public static string InventoryId {
            get {
                return ResourceManager.GetString("InventoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leltár kezdete:.
        /// </summary>
        public static string InventoryRecordBegin {
            get {
                return ResourceManager.GetString("InventoryRecordBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leltár tervezett vége:.
        /// </summary>
        public static string InventoryRecordEnd {
            get {
                return ResourceManager.GetString("InventoryRecordEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string LoginHeaderMessage {
            get {
                return ResourceManager.GetString("LoginHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzített tételek száma:.
        /// </summary>
        public static string NumberOfFixeditems {
            get {
                return ResourceManager.GetString("NumberOfFixeditems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkciók.
        /// </summary>
        public static string StartNavigationValue {
            get {
                return ResourceManager.GetString("StartNavigationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raktár:.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
    }
}
